import os
import httpx
import logging

log = logging.getLogger("TelegramService")

class TelegramService:
    def __init__(self):
        self.token = os.getenv("TELEGRAM_BOT_TOKEN")
        self.chat_id = os.getenv("TELEGRAM_CHAT_ID")
        self.client = httpx.AsyncClient()

    async def send_message(self, text: str):
        if not self.token or not self.chat_id:
            log.warning("Telegram NOT configured. Missing TOKEN or CHAT_ID.")
            return

        url = f"https://api.telegram.org/bot{self.token}/sendMessage"
        try:
            r = await self.client.post(url, json={
                "chat_id": self.chat_id,
                "text": text,
                "parse_mode": "Markdown"
            })
            if r.status_code != 200:
                log.error(f"Telegram error: {r.text}")
        except Exception as e:
            log.error(f"Telegram request failed: {e}")

    async def send_signal_alert(self, coin: str, signal: str, sentiment: float, confidence: float):
        emoji = "🚀" if signal == "BUY" else "🔻" if signal == "SELL" else "⚖️"
        msg = (
            f"{emoji} *TRADING SIGNAL ALERT* {emoji}\n\n"
            f"*Asset:* {coin}\n"
            f"*Action:* {signal}\n"
            f"*Sentiment:* {sentiment:.2f}\n"
            f"*Confidence:* {confidence:.2f}\n"
            f"\n_Generated by Neural Sentiment V1_"
        )
        await self.send_message(msg)

    async def send_msg(self, text: str):
        """Bridge for older calls to send_msg"""
        await self.send_message(text)

telegram_ai = TelegramService()
