"""add bot models

Revision ID: 60aa35df2686
Revises: 6e99922a632c
Create Date: 2025-12-24 01:46:13.953612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60aa35df2686'
down_revision: Union[str, Sequence[str], None] = '6e99922a632c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_logs_id'), 'bot_logs', ['id'], unique=False)
    op.create_index(op.f('ix_bot_logs_timestamp'), 'bot_logs', ['timestamp'], unique=False)
    op.create_table('bot_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('price', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=38, scale=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_trades_id'), 'bot_trades', ['id'], unique=False)
    op.create_index(op.f('ix_bot_trades_symbol'), 'bot_trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_bot_trades_timestamp'), 'bot_trades', ['timestamp'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('heuristic_score', sa.Float(), nullable=True),
    sa.Column('engagement', sa.Float(), nullable=True),
    sa.Column('weighted_impact', sa.Float(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('targets', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_account'), 'signals', ['account'], unique=False)
    op.create_index(op.f('ix_signals_created_at'), 'signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_signals_source'), 'signals', ['source'], unique=False)
    op.create_index(op.f('ix_signals_type'), 'signals', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_source'), table_name='signals')
    op.drop_index(op.f('ix_signals_created_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_account'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_bot_trades_timestamp'), table_name='bot_trades')
    op.drop_index(op.f('ix_bot_trades_symbol'), table_name='bot_trades')
    op.drop_index(op.f('ix_bot_trades_id'), table_name='bot_trades')
    op.drop_table('bot_trades')
    op.drop_index(op.f('ix_bot_logs_timestamp'), table_name='bot_logs')
    op.drop_index(op.f('ix_bot_logs_id'), table_name='bot_logs')
    op.drop_table('bot_logs')
    # ### end Alembic commands ###
