"""enhance transaction schema

Revision ID: 7e60d958e227
Revises: 60aa35df2686
Create Date: 2025-12-24 01:53:12.112469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e60d958e227'
down_revision: Union[str, Sequence[str], None] = '60aa35df2686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_transactions_external_id'), 'transactions', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_external_id'), table_name='transactions')
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'source')
    op.drop_column('transactions', 'external_id')
    # ### end Alembic commands ###
