"""enforce unique external_id

Revision ID: 8ac7921a1725
Revises: 76fea138db79
Create Date: 2025-12-24 02:15:55.819817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ac7921a1725'
down_revision: Union[str, Sequence[str], None] = '76fea138db79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_external_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_external_id'), 'transactions', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_external_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_external_id'), 'transactions', ['external_id'], unique=False)
    # ### end Alembic commands ###
